spring.application.name=tarification-api

# Chemin vers le fichier CSV de simulation budgetaire
# Note : seul le CSV existe dans le projet (pas de .xlsx pour CALC DEP(4))
# Le serveur demarre depuis tarification-api/, donc on remonte d'un niveau avec ../
simulation.fichier.csv=../Donnees/Autres/CALC DEP(4).csv
