spring.application.name=tarification-api
server.port=9090
server.forward-headers-strategy=native

# CONFIGURATION POSTGRESQL (DOCKER / CLOUD)
# ----------------------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mairie_tarifs}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin_password}

# Stratégie de mise à jour de la base (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Chemin vers le fichier XLSX de simulation budgetaire
simulation.fichier.excel=CALC DEP(4).xlsx

