spring.application.name=tarification-api

# Chemin vers le fichier XLSX de simulation budgetaire
# Le serveur demarre depuis tarification-api/, donc on remonte d'un niveau avec ../
simulation.fichier.excel=../Donnees/Autres/CALC DEP(4).xlsx
